feat: CDAs COVID Lab Central
andes/andesMicroservices pull request #105
Opened 2020-11-04 14:28 UTC by plammel

### Requerimiento
* URL de la User Story, referencia al issue (#1111) o breve descripcion del requerimiento
https://proyectos.andes.gob.ar/browse/MISC-106
### Funcionalidad desarrollada 

1.  Microservicio para CDAs de COVID cargados en LAB Central
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

2020-11-05 00:29 UTC, sychus requested changes
Sugerencias importantes:
1) Agregar info al pdf
2) Quitar request (ya q esta descontinuada) y usar got
3) Usar logger en alguna colección para monitorear los eventos de pcr.

2020-11-05 00:29 UTC, sychus commented on cda-laboratorio-central/controller/import-labs.ts
> +                console.error(`Error en download files: ${e}`);
Usaría el paquete logger y guardar este tipo de errores extraños. Sugiero una colección a parte para este caso. ¿Que opinan? @liquid36 @condorpiedra ???

2020-11-05 00:29 UTC, sychus commented on cda-laboratorio-central/controller/import-labs.ts
> +        // if (e && e.error === 'sips-pdf') {
acá también loggear

2020-11-05 00:29 UTC, sychus commented on cda-laboratorio-central/controller/import-labs.ts
> +async function generarAdjunto(cabecera, detalle) {
Agregaría el nombre del efector (en este caso el lab_central). Y además agregaría el solicitante (q ese dato está) y está bueno que el paciente sepa donde le hicieron el hisopado

2020-11-05 00:29 UTC, sychus commented on cda-laboratorio-central/controller/import-labs.ts
> +            console.log(file);
sacar console.log

2020-11-05 00:29 UTC, sychus commented on cda-laboratorio-central/controller/import-labs.ts
> +        pdf.create(html, options).toFile('./arancelamiento.pdf', function (err, file) {
cambiar el nombre del archivo: Se me ocurre usar laboratorio-tipo-fecha. Donde tipo, sería el tipo de análisis en este caso lo tenemos que es pcr y la fecha sería la de validación

2020-11-05 00:29 UTC, sychus commented on cda-laboratorio-central/controller/operations.ts
> +            console.log('url', url)
quitar console

2020-11-05 00:29 UTC, sychus commented on cda-laboratorio-central/controller/operations.ts
> +        console.log('data', data)
quitar los console

2020-11-05 00:29 UTC, sychus commented on cda-laboratorio-central/controller/operations.ts
> +        console.log('options', options)
quitar console

2020-11-05 00:29 UTC, sychus commented on cda-laboratorio-central/controller/operations.ts
> +        request(options, (error, response, body) => {
La librería request está descontinuada. Yo aprovecharía a ir cambiando por esta: https://www.npmjs.com/package/got

2020-11-05 10:41 UTC, liquid36 commented on cda-laboratorio-central/controller/import-labs.ts
> +        pdf.create(html, options).toFile('./arancelamiento.pdf', function (err, file) {
Debe ir como en la API, sin nombre de archivo para que se cree en una carpeta temporal y con nombre temporal. Lo ideal hubiese sido reutilizar toda la lógica que esta en la API.

2020-11-05 10:41 UTC, liquid36 commented on cda-laboratorio-central/controller/import-labs.ts
> +                console.error(`Error en download files: ${e}`);
Siempre y cuando alguien le haga seguimiento, lo que sí cambiarle el texto porque no esta ocurriendo ningún descarga de archivos.

2020-11-05 10:42 UTC, liquid36 commented on cda-laboratorio-central/controller/operations.ts
> +        request(options, (error, response, body) => {
GOT o lo que sea deberíamos tener nuestro propia abstracción porque siempre es la misma discusión.

2020-11-06 02:02 UTC, silviroa requested changes
agregar @andes/log y got en el package.json

2020-11-07 04:40 UTC, sychus commented
Se reemplaza PR

2020-11-07 04:40 UTC, closed without merging