Cda lab central
andes/andesMicroservices pull request #106
Opened 2020-11-07 04:39 UTC by sychus

### Requerimiento
Dado un resultado de laboratorio central, se genera el informe de resultado en formato CDA con pdf de informe.

### Funcionalidad desarrollada 

1. Se generan los cda de los métodos por PCR y Test rápidos.
2. Se genera informe en pdf.
3. Se asocia a la HUDS y en la app mobile del ciudadano.

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

2020-11-07 14:38 UTC, silviroa requested changes

2020-11-07 14:38 UTC, silviroa commented on cda-laboratorio-central/controller/operations.ts
> +    return new Promise( async (resolve: any, reject: any) => {
no deberia ser necesario usar promise aca

2020-11-09 22:16 UTC, silviroa approved these changes

2020-11-10 12:11 UTC, condorpiedra approved these changes

2020-11-10 12:16 UTC, merged