fix(index): soluciona referencia a objeto paciente
andes/andesMicroservices pull request #108
Opened 2020-11-13 06:05 UTC by sychus

### Requerimiento
- Soluciona la referencia al objeto paciente, ya que estaba mal referenciado y no entraba nunca cuando se emitia desde un evento de la api.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

OBS: Recordar instalar la librería oculta en el servidor, ya que sino no es posible generar los pdf.
OBS2: Revisar en el ecosystem del servidor, porque puede haber problemas con las rutas cuando levanta el process.cwd() !!!

2020-11-13 11:05 UTC, condorpiedra requested changes

2020-11-13 11:05 UTC, condorpiedra commented on cda-laboratorio-central/index.ts
> +        const paciente = req.body.data;  // Ojo que el objeto paciente viene en data ahora
Si se utiliza el evento mobile:patient:login, el paciente viene en req.body.data.pacientes[0];

2020-11-13 11:06 UTC, condorpiedra commented
evitar subir el package-lock si no hay cambios en el package.json

2020-11-16 12:54 UTC, sychus commented on cda-laboratorio-central/index.ts
> +        const paciente = req.body.data;  // Ojo que el objeto paciente viene en data ahora
Solved!

2020-11-18 18:36 UTC, liquid36 approved these changes

2020-11-18 18:37 UTC, condorpiedra approved these changes

2020-11-18 18:48 UTC, merged