Nomivac - Reemplaza peticion sql por api rest de sisa
andes/andesMicroservices pull request #112
Opened 2020-12-14 14:16 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/IO-14

### Funcionalidad desarrollada 

1. Reemplaza request para importacion de vacunas

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2020-12-19 21:31 UTC, silviroa commented on cda-nomivac/controller/sisa.ts
> +                    texto: texto + `Vacuna: ${vacunas[i].sniVacunaNombre} Dosis: ${vacunas[i].sniDosisOrden} Esquema: ${vacunas[i].sniVacunaEsquemaNombre} pertenece al lote: ${vacunas[i].Lote}`
El texto o nombre de la dosis viene en el parametro "sniDosisNombre".

2020-12-19 21:31 UTC, silviroa commented on cda-nomivac/controller/sisa.ts
> +                    idvacuna: vacunas[i].idSniVacuna.toString(),
Hay dos campos que seria interesante guardar aquí... uno él el código de identificación del tipo de vacuna "idSniVacuna" y la identificación de la aplicación "idSniAplicacion".
EL control de duplicidad en la api se realiza por el campo idVacuna, así que en ese campo debería ir el  "idSniAplicacion". Agreguemos otro campo que sea "codigo"  y tenga el dato de "idSniVacuna".

2020-12-20 00:04 UTC, silviroa requested changes

2020-12-20 00:04 UTC, silviroa commented on cda-nomivac/controller/sisa.ts
> +                    efector: vacunas[i].origenNombre
Agregar los campos esquema y condición, que vienen en el dato "sniVacunaEsquemaNombre" y "sniAplicacionCondicionNombre"

2020-12-21 15:57 UTC, sychus requested changes
Cambiaría esos detalles para usar la última versión del post que recomienda sisa.

2020-12-21 15:57 UTC, sychus commented on cda-nomivac/service/nomivacWSsisa.ts
> +            Accept: 'application/json'
Acá en el header deberíamos agregar lo siguiente:
app_id = 'valor'
app_key= 'valor'

2020-12-21 15:57 UTC, sychus commented on cda-nomivac/service/nomivacWSsisa.ts
> +            password: sisaDev.password,
Esto lo podemos sacar del json

2020-12-21 17:54 UTC, condorpiedra commented on cda-nomivac/service/nomivacWSsisa.ts
> +            Accept: 'application/json'
No aplica

2020-12-21 17:54 UTC, condorpiedra commented on cda-nomivac/service/nomivacWSsisa.ts
> +            password: sisaDev.password,
No aplica

2020-12-21 17:56 UTC, condorpiedra commented on cda-nomivac/controller/sisa.ts
> +                    texto: texto + `Vacuna: ${vacunas[i].sniVacunaNombre} Dosis: ${vacunas[i].sniDosisOrden} Esquema: ${vacunas[i].sniVacunaEsquemaNombre} pertenece al lote: ${vacunas[i].Lote}`
cambios realizados

2020-12-21 17:56 UTC, merged