feat: export profesional SISA
andes/andesMicroservices pull request #114
Opened 2021-01-14 15:35 UTC by plammel

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-42

### Funcionalidad desarrollada 

1. Microservicio para exportar profesionales matriculados a SISA
2. 
3. 

### UserStory llegó a completarse

- [ ] Si https://proyectos.andes.gob.ar/browse/MAT-42

- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si https://github.com/andes/api/pull/1250
- [ ] No

2021-01-15 11:47 UTC, condorpiedra requested changes

2021-01-15 11:47 UTC, condorpiedra commented on profesional_sisa/service/operaciones.service.ts
> +const got = require('got');
No es necesario usar esta librería debería resolverse todo con node-fetch

2021-01-15 11:47 UTC, condorpiedra commented on profesional_sisa/index.ts
> +        console.log('prof',prof);
eliminar console.log

2021-02-18 17:50 UTC, MCele requested changes

2021-02-18 17:50 UTC, MCele commented on profesional_sisa/service/operaciones.service.ts
> +    const { error, statusCode, body } = await fetch(url, options);
Por las pruebas que realice entiendo que la variable "statusCode" debería ser "status"

2021-02-18 20:02 UTC, MCele submitted a review, later dismissed

2021-02-23 19:04 UTC, condorpiedra approved these changes

2021-02-23 19:09 UTC, merged