Misc 169
andes/andesMicroservices pull request #141
Opened 2021-08-05 13:57 UTC by MCele

### Requerimiento

https://proyectos.andes.gob.ar/browse/MISC-169

### Funcionalidad desarrollada 

1. Se modifica la forma de obtener el idTipoNomenclador por medio un procedimiento de SIPS.
2. Se agrega la facturación para prepagas, que se había perdido hace tiempo.
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2021-08-20 12:37 UTC, plammel requested changes

2021-08-20 12:37 UTC, plammel commented on facturacion/facturar/recupero-financiero/query-recupero.ts
> +        return err;
En lugar de retornar el error, metería un log `log(fakeRequestSql, ......)`

2021-08-20 12:37 UTC, plammel commented on facturacion/facturar/recupero-financiero/query-recupero.ts
> + */
Bien ahí el comentario! 👏

2021-10-07 18:07 UTC, MCele commented on facturacion/facturar/recupero-financiero/query-recupero.ts
> +        return err;
Agregado!

2021-12-09 16:50 UTC, plammel approved these changes

2021-12-15 17:45 UTC, martinebucarey approved these changes

2021-12-15 17:46 UTC, merged