PERINATAL - Agregar ingreso numérico para mas de 10 embarazos
andes/andesMicroservices pull request #199
Opened 2022-07-29 02:38 UTC by leon-bravo

### Requerimiento

[PER-72](https://proyectos.andes.gob.ar/browse/PER-72) - Molécula "embarazo" agregar numero

### Funcionalidad desarrollada 

1. Se agrega chequeo que permite agregar un valor numerico para cuando se selecciona mas de 10 embarazos
2. 
3. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2022-08-24 13:21 UTC, MCele requested changes

2022-08-24 13:21 UTC, MCele commented on sip-plus-perinatal/controller/sip-plus.ts
> +            if (numEmbarazo === '11') {
creo que todo esto se podría resolver dentro de mismo método getNumGesta

2022-08-24 17:08 UTC, leon-bravo commented on sip-plus-perinatal/controller/sip-plus.ts
> +            if (numEmbarazo === '11') {
ahi hice la correccion, cualquier cosa avisame

2022-10-06 15:55 UTC, MarianoCampetella approved these changes

2022-11-04 20:21 UTC, MCele approved these changes

2022-11-14 18:36 UTC, merged