MS - APIs Whatsapp
andes/andesMicroservices pull request #218
Opened 2024-07-03 15:52 UTC by JuanIRamirez

### Requerimiento

https://proyectos.andes.gob.ar/browse/MISC-345

### Funcionalidad desarrollada 

1. Nuevo microservice: Notificaciones.
2. Rutas:  post('/sendMessage'): Enviar mensaje. 
               get('/fetchMessages'): Obtener mensajes de un chat.
               post('/sendMedia'): Enviar archivo (binary).
               post('/sendLocation): Enviar localización.
3. Verificar en config.private MONGO_HOST y MONGO_LOG
4. Al dar un turno OJO con el nro de celular, usar nro propio.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [X] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2024-07-04 15:33 UTC, negro89 approved these changes

2024-07-04 16:26 UTC, silviroa requested changes
Agregaría tmb que en el index no es necesario esperar la resolución del envío del mensaje para hacer el res.json, me preocupa la cantidad de request que van a llegar en paralelo a ese MS

2024-07-04 16:26 UTC, silviroa commented on notificaciones/controller/notificaciones.ts
quitar console.log()

2024-07-04 16:26 UTC, silviroa commented on notificaciones/controller/notificaciones.ts
> +
No sería mejor definir estas variables en ámbitos locales a las funciones y pasarlas como parámetro.

2024-07-05 11:50 UTC, silviroa approved these changes

2024-07-05 15:15 UTC, merged